server:
  port: 8001
  

spring:
   application:
    name: webPagesApplication
   http:
     encoding:
       charset: utf-8
       force: true
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://10.2.1.100:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: webPagesApplication
    prefer-ip-address: true     #访问路径可以显示IP地址
 
